from __future__ import annotations

import datetime
from pathlib import Path

from rich.console import Console

from .agent_runner import run_openhands_doc_agent
from .git_utils import (
    GitError,
    checkout_new_branch,
    clone_repo,
    commit_all,
    ensure_empty_dir,
    get_default_branch,
    init_empty_repo_with_initial_commit,
    push_branch,
    repo_has_commits,
    set_push_remote_with_token,
)
from .github import create_pull_request, get_repo_default_branch, parse_github_repo
from .prompt import build_docgen_prompt

console = Console()


def run_pipeline(
    *,
    source: str,
    target: str,
    coverage: str,
    workspace: Path,
    base_branch: str | None,
    llm_model: str,
    llm_api_key: str,
    llm_base_url: str | None,
    github_token: str | None,
    dry_run: bool,
) -> str | None:
    ws = workspace.expanduser().resolve()
    ws.mkdir(parents=True, exist_ok=True)

    source_dir = ws / "source"
    target_dir = ws / "target"

    console.print(f"Workspace: {ws}")

    ensure_empty_dir(source_dir)
    ensure_empty_dir(target_dir)

    console.print(f"Cloning source repo: {source}")
    clone_repo(_normalize_repo_url(source), source_dir)

    console.print(f"Cloning target repo: {target}")
    clone_repo(_normalize_repo_url(target), target_dir)

    gh = parse_github_repo(target)

    if base_branch is None:
        try:
            base_branch = get_default_branch(target_dir)
        except GitError:
            base_branch = get_repo_default_branch(repo=gh, token=github_token) or "main"

    if not repo_has_commits(target_dir):
        console.print(
            f"Target repo has no commits; creating an initial commit on '{base_branch}' so PRs can be opened."
        )
        init_empty_repo_with_initial_commit(target_dir, base_branch=base_branch)

        if not dry_run:
            if not github_token:
                raise RuntimeError("github_token is required unless dry_run is set")

            set_push_remote_with_token(target_dir, token=github_token, owner=gh.owner, repo=gh.name)
            console.print(f"Pushing initial base branch: {base_branch}")
            push_branch(target_dir, base_branch)

    branch = _make_branch_name(source)
    checkout_new_branch(target_dir, branch)

    prompt = build_docgen_prompt(
        source_dir=source_dir,
        target_dir=target_dir,
        source_repo=source,
        coverage=coverage,
    )

    console.print("Running OpenHands doc agent...")
    run_openhands_doc_agent(
        workspace=ws,
        prompt=prompt,
        llm_model=llm_model,
        llm_api_key=llm_api_key,
        llm_base_url=llm_base_url,
    )

    commit_all(target_dir, f"docs: add Mintlify technical docs for {source}")

    if dry_run:
        console.print("Dry-run enabled: skipping push and PR creation.")
        return None

    if not github_token:
        raise RuntimeError("github_token is required unless dry_run is set")

    set_push_remote_with_token(target_dir, token=github_token, owner=gh.owner, repo=gh.name)

    console.print(f"Pushing branch: {branch}")
    push_branch(target_dir, branch)

    pr_title = f"Add Mintlify technical docs for {source}"
    pr_body = (
        "This PR was generated by an OpenHands Software Agent SDK doc-generation agent.\n\n"
        "Preview locally (in this repo):\n\n"
        "```bash\n"
        "npx mintlify dev\n"
        "```\n"
    )

    console.print("Creating GitHub PR...")
    pr_url = create_pull_request(
        repo=gh,
        token=github_token,
        head=branch,
        base=base_branch,
        title=pr_title,
        body=pr_body,
    )

    return pr_url


def _make_branch_name(source: str) -> str:
    stamp = datetime.datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    slug = source.rstrip("/").split("/")[-1].replace(".git", "")
    return f"docs/repodoc-{slug}-{stamp}"


def _normalize_repo_url(repo: str) -> str:
    repo = repo.strip()
    if repo.startswith("http://") or repo.startswith("https://"):
        return repo
    return f"https://github.com/{repo}"
